-- TAO DATABASE
CREATE DATABASE BTVN

-- TAO TABLE 
CREATE TABLE SV (
MASV	NVARCHAR(10)	PRIMARY KEY,
HOSV	NVARCHAR(20)	NOT NULL,
TENSV	NVARCHAR(20)	NOT NULL,
PHAI	BIT	NOT NULL,
NGAYSINH	DATE	NULL,
NOISINH	NVARCHAR(20)	NULL)

CREATE TABLE DMMH(
MAMH	NVARCHAR(10)	PRIMARY KEY,
TENMH	NVARCHAR(20)	NOT NULL,
SOTIET	INT	NULL)

CREATE TABLE KETQUA(
MASV	NVARCHAR(10)	NOT NULL,
MAMH	NVARCHAR(10)	NOT NULL,
DIEM_Q	INT		NULL,
DIEM_L	INT		NULL,
DIEM_AS INT		NULL)

ALTER TABLE KETQUA
ADD CONSTRAINT HS01
PRIMARY KEY (MASV,MAMH)

ALTER TABLE KETQUA 
ADD CONSTRAINT HD01
FOREIGN KEY (MASV)
REFERENCES SV(MASV)

ALTER TABLE KETQUA
ADD CONSTRAINT MH01
FOREIGN KEY (MAMH)
REFERENCES DMMH(MAMH)

INSERT INTO SV
VALUES	('SE171385','Trương','Điền Phú',1,'2003-02-26','Ho Chi Minh city')
INSERT INTO SV
VALUES	('SE171292','Nguyễn','Hoàng Anh',1,'2003-03-26','Ho Chi Minh city')
INSERT INTO SV
VALUES	('SE171387','Nguyễn','Phan Nhật Minh',1,'2003-04-26','Ho Chi Minh city')
INSERT INTO SV
VALUES	('SE171338','Cao','Thùy Dương',1,'2003-05-26','Ho Chi Minh city')
INSERT INTO SV
VALUES	('SE171230','Lý','Đoàn Vân Anh',0,'2003-06-26','Ho Chi Minh city')
INSERT INTO SV
VALUES	('SE171177','Nguyễn','Minh Đăng',1,'2003-07-26','Ho Chi Minh city')

INSERT INTO DMMH(MAMH,TENMH,SOTIET)
VALUES ('MAE101','Mathematics for engineering','30')
INSERT INTO DMMH
VALUES ('CEA101','Computer Organization and Architecture','30')
INSERT INTO DMMH
VALUES ('CSI104','Introduction to computing','30')
INSERT INTO DMMH
VALUES ('PFP191','Programming fundemental with Python','30')
INSERT INTO DMMH
VALUES ('SSL101c','Academic Skills for University Success','4')
INSERT INTO DMMH
VALUES ('VOV124','Vovinam 2','30')

INSERT INTO KETQUA
VALUES ('SE171385','MAE101',5,5,5)
INSERT INTO KETQUA
VALUES ('SE171385','CEA101',7,8,8)
INSERT INTO KETQUA
VALUES ('SE171385','CSI104',9,7,8)
INSERT INTO KETQUA
VALUES ('SE171385','PFP191',9,6,7)
INSERT INTO KETQUA
VALUES ('SE171385','SSL101c',7,7,8)
INSERT INTO KETQUA
VALUES ('SE171385','VOV124',5,5,5)
----------------------------------------------------------------------
--CAU 4A
SELECT SUM(CASE PHAI WHEN 1 THEN 1 ELSE 0 END) AS 'NAM',
	   SUM (CASE PHAI WHEN 0 THEN 1 ELSE 0 END) AS 'NỮ'
FROM SV 

--CAU4B
SELECT SV.MASV, SV.HOSV,SV.TENSV,KQ.MAMH,KQ.DIEM_L,KQ.DIEM_Q,KQ.DIEM_AS,((KQ.DIEM_L+KQ.DIEM_Q+KQ.DIEM_AS)/3) AS DIEM_TB
FROM KETQUA KQ JOIN SV 
ON SV.MASV=KQ.MASV 
ORDER BY DIEM_TB ASC

--CAU4C
SELECT 

