CREATE DATABASE QLNHATRO_NHOM2


CREATE TABLE NGUOIDUNG(
MAND	INT		PRIMARY KEY,
TENND	NVARCHAR(20)	NOT NULL,
GIOITINH	BIT		NOT NULL,
DIENTHOAI	NVARCHAR(20)	NOT NULL,
DIACHI	NVARCHAR(20)	NOT NULL,
QUAN	NVARCHAR(20)	NOT NULL,
EMAIL	NVARCHAR(20)		NOT NULL)
 
IF OBJECT_ID ('INSERTNGUOIDUNG') IS NOT NULL
	DROP PROC INSERTNGUOIDUNG
GO 
CREATE PROC INSERTNGUOIDUNG 
	@MAND	INT,		
	@TENND	NVARCHAR(20),
	@GIOITINH	BIT,
	@DIENTHOAI	NVARCHAR(20),
	@DIACHI	NVARCHAR(20),
	@QUAN	NVARCHAR(20),
	@EMAIL	NVARCHAR(20)
AS
	INSERT NGUOIDUNG 
	VALUES (@MAND,@TENND,@GIOITINH,@DIENTHOAI,@DIACHI,@QUAN,@EMAIL)
PRINT(N'ADD SUCCESSFULLY')

EXEC INSERTNGUOIDUNG @MAND = 1, @TENND = N'Minh', @GIOITINH = 0, @DIENTHOAI = '0978173990', @DIACHI = N'506 Ba Tháng 2', @QUAN = N'Quận 10', @EMAIL = N'minhtn@gmail.com'
EXEC INSERTNGUOIDUNG @MAND = 2, @TENND = N'Tâm', @GIOITINH = 1, @DIENTHOAI = '0123456789', @DIACHI = N'7 Lý Thường Kiệt', @QUAN = N'Quận 10', @EMAIL = N'tamlt@gmail.com'
EXEC INSERTNGUOIDUNG @MAND = 3, @TENND = N'Lộc', @GIOITINH = 1, @DIENTHOAI = '01884981234', @DIACHI = N'4 Ngô Gia Tự', @QUAN = N'Quận 10', @EMAIL =  N'loccd@gmail.com'
EXEC INSERTNGUOIDUNG @MAND = 4, @TENND = N'Hoàn', @GIOITINH = 1, @DIENTHOAI = '0912345678', @DIACHI = N'8 Điện Biên Phủ', @QUAN = N'Quận Bình Thạnh', @EMAIL =  N'hoannv@gmail.com'
EXEC INSERTNGUOIDUNG @MAND = 5, @TENND = N'Nhân', @GIOITINH = 1, @DIENTHOAI = '0967456123', @DIACHI = N'7 Điện Biên Phủ', @QUAN =N'Quận Bình Thạnh', @EMAIL = N'nhannt@gmail.com'
EXEC INSERTNGUOIDUNG @MAND = 6, @TENND = N'Hiếu', @GIOITINH = 1, @DIENTHOAI = '0965234567', @DIACHI = N'8 Nguyễn Thái Sơn', @QUAN = N'Quận Gò Vấp', @EMAIL = N'hieunt@gmail.com'
EXEC INSERTNGUOIDUNG @MAND = 7, @TENND = N'Dung', @GIOITINH = 0, @DIENTHOAI = '0956123456', @DIACHI = N'10 CMT8', @QUAN = N'Quận 1', @EMAIL = N'dungnt@gmail.com'
EXEC INSERTNGUOIDUNG @MAND = 8, @TENND = N'Yến', @GIOITINH = 0, @DIENTHOAI = '0977456789', @DIACHI = N'23 Lý Tự Trọng', @QUAN =  N'Quận 1', @EMAIL = N'yentm@gmail.com'
EXEC INSERTNGUOIDUNG @MAND = 9, @TENND = N'Anh', @GIOITINH = 0, @DIENTHOAI = '0945321654', @DIACHI = N'610 Nguyễn Trãi', @QUAN = N'Quận 5', @EMAIL =  N'anhnnt@gmail.com'
EXEC INSERTNGUOIDUNG @MAND = 10, @TENND = N'Thịnh', @GIOITINH = 1, @DIENTHOAI = '0166894567', @DIACHI = N'20 Kinh Dương Vương', @QUAN = N'Quận Bình Tân', @EMAIL = N'thinhtp@gmail.com'

CREATE TABLE LOAINHA(
MALN	VARCHAR(20)		PRIMARY KEY,
TENLN	VARCHAR(20)		NOT NULL)
IF OBJECT_ID ('INSERTLOAINHA') IS NOT NULL 
	DROP PROC INSERTLOAINHA
GO 

CREATE PROC INSERTLOAINHA
	@MALN	VARCHAR(20),
	@TENLN	VARCHAR(20)	
AS 
	INSERT LOAINHA 
	VALUES (@MALN,@TENLN)

EXEC INSERTLOAINHA @MALN = 'CC',@TENLN= N'Căn hộ chung cư'
EXEC INSERTLOAINHA @MALN='NR',@TENLN= N'Nhà riêng'
EXEC INSERTLOAINHA @MALN='PT',@TENLN= N'Phòng trọ khép kín'

CREATE TABLE NHATRO(
MANT	NVARCHAR(10)		PRIMARY KEY,
LOAIHINHNT		VARCHAR(20)		NOT NULL,
DIENTICH	INT		NOT NULL,
GIAPHONG	DECIMAL		NOT NULL,
DIACHINT	NVARCHAR(20)	NOT NULL,
QUAN		NVARCHAR(20)	NOT NULL,
MOTA	NVARCHAR(20)	NULL,
NGAYDANG	DATE	NOT NULL,
NGUOILIENHE		INT		NOT NULL)

 IF OBJECT_ID ('INSERTNHATRO') IS NOT NULL 
	DROP PROC INSERTNHATRO
GO 

CREATE PROC INSERTNHATRO 
	@MANT	NVARCHAR(10),
	@LOAIHINHNT		VARCHAR(20),
	@DIENTICH	INT,
	@GIAPHONG	DECIMAL,
	@DIACHINT	NVARCHAR(20),
	@QUAN		NVARCHAR(20),
	@MOTA	NVARCHAR(20),
	@NGAYDANG	DATE,
	@NGUOILIENHE		INT	
AS 
IF EXISTS (SELECT* FROM LOAINHA WHERE MALN=@LOAIHINHNT) AND EXISTS (SELECT* FROM NGUOIDUNG WHERE MAND=@NGUOILIENHE)
	BEGIN 
		INSERT NHATRO
		VALUES (@MANT,@LOAIHINHNT,@DIENTICH,@GIAPHONG,@DIACHINT,@QUAN,@MOTA,@NGAYDANG,@NGUOILIENHE)
	END
ELSE
	BEGIN 
	RAISERROR ('NOT A VALID MALN AND MAND',11,1)
	END 

BEGIN TRY 
	EXEC INSERTNHATRO '100','CC', 100, 1000, N'23 Lý Thường Kiệt', N'Quận 10', N'Thoáng mát', '2013-01-22', 3
	EXEC INSERTNHATRO '101','NR', 300, 3000, N'73 Nơ Trang Long', N'Quận Bình Thạnh', N'Sạch sẽ', '2013-03-12', 5
	EXEC INSERTNHATRO '102','PT', 25, 200, N'606 Ba Tháng Hai', N'Quận 10', N'An ninh', '2013-10-06', 1
	EXEC INSERTNHATRO '103','PT', 35, 300, N'656 CMT8', N'Quận 10', N'Phòng Đúc', '2013-09-09', 2
	EXEC INSERTNHATRO '104','NR', 400, 6000, N'8 Nguyễn Trãi', N'Quận 5', N'Mặt tiền', '2013-04-05', 1
	EXEC INSERTNHATRO '105','NR', 300, 8000, N'2 Bùi Thị Xuân', N'Quận 1', N'Mới xây', '2013-02-03', 1
	EXEC INSERTNHATRO '106','CC', 150, 6000, N'6 Ngô Gia Tự', N'Quận 10', N'Gần trường học', '2013-03-04', 4
	EXEC INSERTNHATRO '107','CC', 600, 10000, N'1 Nguyễn Du', N'Quận 1', N'Ngay trung tâm', '2013-02-03', 8
	EXEC INSERTNHATRO '108','PT', 14, 150, N'2 Bạch Đằng', N'Quận Bình Thạnh', N'Gần chợ', '2013-05-06', 2
	EXEC INSERTNHATRO '109','PT', 25, 300, N'6 Hoàng Văn Thụ', N'Quận Tân Bình', N'Gần sân bay', '2013-09-04', 6
	EXEC INSERTNHATRO '110','CC', 250, 6000, N'2D City Land', N'Quận 7', N'Mới xây', '2013-05-06', 9
END TRY 
BEGIN CATCH
    PRINT   'An error occurred.'
    PRINT   'Message: ' + CONVERT(varchar, ERROR_MESSAGE())
    IF ERROR_NUMBER() = 50000
        PRINT    'This is a custom error message.'
END CATCH

CREATE TABLE DANHGIA(
MADG	INT		PRIMARY KEY,
NGUOIDG		INT		NOT NULL,
CHATLUONG	NVARCHAR(20)		NULL,
TRANGTHAIDG		BIT		NOT NULL,
NOIDUNGDG	NVARCHAR(20)	NOT NULL,
MANT	INT		NOT NULL)

IF OBJECT_ID ('INSERTDANHGIA') IS NOT NULL 
	DROP PROC INSERTDANHGIA
GO 

CREATE PROC INSERTDANHGIA 
	@MADG	INT,
	@NGUOIDG		INT,
	@CHATLUONG	NVARCHAR(20),
	@TRANGTHAIDG		BIT,
	@NOIDUNGDG	NVARCHAR(20),
	@MANT	INT

AS 
	IF EXISTS (SELECT* FROM NHATRO WHERE MANT=@MANT)
		BEGIN 
			INSERT DANHGIA 
			VALUES (@MADG,@NGUOIDG,@CHATLUONG,@TRANGTHAIDG,@NOIDUNGDG,@MANT)
		END
	ELSE
		BEGIN 
			RAISERROR('NOT A VALID MANT',11,1)
		END
BEGIN TRY 
	EXEC INSERTDANHGIA 500, 8, N'Tốt', 1, N'Đẹp', 103
	EXEC INSERTDANHGIA 501, 6, N'Kém', 0, N'Không an ninh', 108
	EXEC INSERTDANHGIA 502, 8, N'Trung Bình', 0, N'Thiếu ánh sáng', 104
	EXEC INSERTDANHGIA 503, 2, N'Tốt', 1, N'Giá cả hợp lí', 102
	EXEC INSERTDANHGIA 504, 7, N'Tốt', 1, N'Giao thông thuận lợi', 108
	EXEC INSERTDANHGIA 505, 1, N'Trung Bình', 0, N'Không an ninh', 104
	EXEC INSERTDANHGIA 506, 8, N'Tốt', 1, N'Nhà đẹp', 103
	EXEC INSERTDANHGIA 507, 9, N'Kém', 0, N'Ồn ào', 109
	EXEC INSERTDANHGIA 508, 6, N'Trung Bình', 0, N'Đường đi hẹp', 105
	EXEC INSERTDANHGIA 509, 3, N'Tốt', 1, N'Chủ nhà tốt', 107
	EXEC INSERTDANHGIA 510, 8, N'Tốt', 1, N'Giá tốt', 103
END TRY 
BEGIN CATCH 
	PRINT 'An error occurred.'
    PRINT   'Message: ' + CONVERT(varchar, ERROR_MESSAGE())
    IF ERROR_NUMBER() = 50000
        PRINT    'This is a custom error message.'
END CATCH
--------------------------------------------------------------------------

IF OBJECT_ID ('CAU_2A') IS NOT NULL
	DROP PROC CAU_2A
GO

CREATE PROC CAU_2A
AS
	SELECT (N'Cho thuê phòng trọ tại '+ DIACHINT +' '+ NT.QUAN) AS CHI_TIẾT, 
			REPLACE (CONVERT(varchar,NT.DIENTICH),'.',',') +'m2' AS DIỆN_TÍCH,
			REPLACE (CONVERT(varchar,NT.GIAPHONG),'.',',') AS GIÁ_PHÒNG,
			MOTA AS MÔ_TẢ,
			CONVERT (varchar,NT.NGAYDANG,103) AS NGÀY_ĐĂNG,
			(CASE GIOITINH 
				WHEN 1 THEN ('A.' + TENND)
				ELSE ('C.' +TENND)
				END ) AS NGƯỜI_LIÊN_HỆ,
			DIENTHOAI AS ĐIỆN_THOẠI,
			DIACHI AS ĐỊA_CHỈ_NGƯỜI_LIÊN_HỆ
	FROM NHATRO NT JOIN NGUOIDUNG ND
	ON NT.NGUOILIENHE = ND.MAND

EXEC CAU_2A

IF OBJECT_ID('CAU_2B') IS NOT NULL
	DROP FUNCTION  CAU_2B
GO 

CREATE FUNCTION  CAU_2B 
	(@TENND	NVARCHAR(20),
	@GIOITINH	BIT,
	@DIENTHOAI	NVARCHAR(20),
	@DIACHI	NVARCHAR(20),
	@QUAN	NVARCHAR(20),
	@EMAIL	NVARCHAR(20))
RETURNS int 
AS
	BEGIN
		RETURN 
			(SELECT MAND
			FROM NGUOIDUNG 
			WHERE TENND=@TENND AND @GIOITINH=GIOITINH AND @DIENTHOAI=DIENTHOAI AND @DIACHI=DIACHI AND @QUAN=QUAN AND @EMAIL= EMAIL )
	END 
	GO 


SELECT dbo.CAU_2B(N'Minh', 0, '0978173990', N'506 Ba Tháng 2', N'Quận 10', N'minhtn@gmail.com')

IF OBJECT_ID('CAU_2C') IS NOT NULL 
	DROP PROC CAU_2C
GO 

CREATE PROC CAU_2C
@MANT	NVARCHAR(10)
AS
	SELECT NT.MANT AS MANT, 
			SUM (CASE TRANGTHAIDG 
			WHEN 1 THEN 1
			ELSE 0
			END) AS SỐ_LIKE,
			SUM (CASE TRANGTHAIDG
			WHEN 0 THEN 1 
			ELSE 0
			END) AS SỐ_DISLIKE
	FROM DANHGIA DG JOIN NHATRO NT
	ON DG.MANT=NT.MANT
	WHERE @MANT =NT. MANT
	GROUP BY NT.MANT

EXEC CAU_2C @MANT=103
	
IF OBJECT_ID ('CAU_2D') IS NOT NULL 
	DROP VIEW CAU_2D
GO 

CREATE VIEW CAU_2D
AS
SELECT TOP(10)
		REPLACE(CONVERT(varchar,NT.DIENTICH),'.',',') + 'm2' AS DIỆN_TÍCH,
		NT.MOTA AS MÔ_TẢ,
		CONVERT (varchar,NT.NGAYDANG,103) AS NGÀY_ĐĂNG,
		ND.TENND AS TÊN_NGƯỜI_LIÊN_HỆ,
		ND.DIACHI AS ĐỊA_CHỈ,
		ND.EMAIL AS EMAIL,
		COUNT(DG.TRANGTHAIDG) AS SỐ_LIKE
FROM DANHGIA DG JOIN NHATRO NT
	ON DG.MANT=NT.MANT
	JOIN NGUOIDUNG ND 
	ON ND.MAND=NT.NGUOILIENHE
WHERE TRANGTHAIDG = 1
GROUP BY NT.DIENTICH,NT.GIAPHONG,NT.MOTA,ND.TENND,ND.DIACHI,NT.NGAYDANG,ND.DIENTHOAI,ND.EMAIL
ORDER BY SỐ_LIKE DESC

SELECT* FROM CAU_2D

IF OBJECT_ID ('CAU_2E') IS NOT NULL 
	DROP PROC CAU_2E
GO 

CREATE PROC CAU_2E 
	@MANT INT 
AS 
	SELECT NT.MANT AS N'MÃ NHÀ TRỌ',
		   ND.TENND AS N'TÊN NGƯỜI ĐÁNH GIÁ',
		   CASE DG.TRANGTHAIDG WHEN 1 THEN 'LIKE'
		   ELSE 'DISLIKE'
		   END AS N'TRẠNG THÁI ĐÁNH GIÁ',
		   DG.NOIDUNGDG AS N'NỘI DUNG ĐÁNH GIÁ'
	FROM NGUOIDUNG ND JOIN DANHGIA DG
		ON ND.MAND =DG.NGUOIDG
		JOIN NHATRO NT
		ON NT.MANT=DG.MANT
	WHERE @MANT=NT.MANT

EXEC CAU_2E @MANT=103

IF OBJECT_ID ('fnCAU_3A') IS NOT NULL 
	DROP FUNCTION fnCAU_3A
GO 

CREATE FUNCTION fnCAU_3A
	

IF OBJECT_ID ('CAU_3A') IS NOT NULL 
	DROP PROC CAU_3A
GO 

CREATE PROC CAU_3A
	@TONGDISLIKE INT
AS
	DELETE FROM DANHGIA
	WHERE SUM(CASE DG.TRANGTHAIDG WHEN 0 THEN 1 ELSE 0 END) > @TONGDISLIKE OR SUM(CASE DG.TRANGTHAIDG WHEN 0 THEN 1 ELSE 0 END) = @TONGDISLIKE
	ALTER TABLE NHATRO DROP CONSTRAINT 
